version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 8080:8080
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000